Document: missinglib
Title: Debian missinglib Manual
Author: <insert document author here>
Abstract: This manual describes what missinglib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/missinglib/missinglib.sgml.gz

Format: postscript
Files: /usr/share/doc/missinglib/missinglib.ps.gz

Format: text
Files: /usr/share/doc/missinglib/missinglib.text.gz

Format: HTML
Index: /usr/share/doc/missinglib/html/index.html
Files: /usr/share/doc/missinglib/html/*.html

  
